"""Initial migration

Revision ID: 693f87a99268
Revises: 2b916250b761
Create Date: 2026-04-30 08:47:07.903893
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '693f87a99268'
down_revision: Union[str, None] = '2b916250b761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
